=== sy2481/taisu-java-center/ruoyi-common/src/main/java/com/ruoyi/common/shardbatis/builder/shardbatis-config.dtd
<?xml version="1.0" encoding="UTF-8"?>

        <!ELEMENT shardingConfig (ignoreList?,parseList?,factoryCode?,strategy*)>
        <!ELEMENT ignoreList (value+)>
        <!ELEMENT parseList (value+)>
        <!ELEMENT factoryCode (value+)>
        <!ELEMENT value (#PCDATA)>
        <!ELEMENT strategy EMPTY>
        <!ATTLIST strategy
                tableName CDATA #REQUIRED
                strategyClass CDATA #REQUIRED
                >

=== sy2481/taisu-java-center/ruoyi-admin/src/main/resources/mybatis/shard-config.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE shardingConfig
PUBLIC "-//mybatis.org//DTD Config 3.0//EN"
"c:\shardbatis-config.dtd">
<shardingConfig>
    <!-- ignoreList可选配置 ignoreList配置的mapperId会被分表参加忽略解析,不会对sql进行修改，value可配置多个 -->
    <ignoreList>
        <value></value>
    </ignoreList>
    <!-- parseList可选配置 如果配置了parseList,只有在parseList范围内并且不再ignoreList内的sql才会被解析和修改，value可配置多个 -->
    <parseList>
        <value></value>
    </parseList>
    <factoryCode>
        <value>AE</value>
    </factoryCode>
    <!-- 配置分表策略 -->
    <strategy tableName="man_work"
              strategyClass="com.ruoyi.common.shardbatis.strategy.impl.TsShardStrategy" />
    <strategy tableName="man_factory"
              strategyClass="com.ruoyi.common.shardbatis.strategy.impl.TsShardStrategy" />
    <strategy tableName="man_work_factory"
              strategyClass="com.ruoyi.common.shardbatis.strategy.impl.TsShardStrategy" />
    <strategy tableName="oa_max_info"
              strategyClass="com.ruoyi.common.shardbatis.strategy.impl.TsShardStrategy" />
    <strategy tableName="man_black_info"
              strategyClass="com.ruoyi.common.shardbatis.strategy.impl.TsShardStrategy" />
</shardingConfig>
